apply plugin: 'com.android.application'

android {
    compileSdkVersion 35
    buildToolsVersion "35.0.0"
    namespace 'droid.cigcounter'

    defaultConfig {
        applicationId "droid.cigcounter"
        minSdkVersion 29
        targetSdkVersion 35
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    lint {
        disable 'InvalidPackage'
        checkReleaseBuilds false
    }
}

